plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file('src/main/resources/potatoptimize.accesswidener')
    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
        mixinConfig 'potatoptimize.mixins.json'
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

    compileOnly(annotationProcessor('io.github.llamalad7:mixinextras-common:0.3.5'))
    implementation(include('io.github.llamalad7:mixinextras-forge:0.3.5'))
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

jar {
    from('LICENSE') {
        rename { "LICENSE_${project.archives_base_name}" }
    }
    manifest {
        attributes([
            'Specification-Title': 'potatoptimize',
            'Specification-Vendor': 'Tater-Certified / Forge 1.20.1 port',
            'Specification-Version': '1',
            'Implementation-Title': project.archives_base_name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Tater-Certified / Herbertofury port',
            'MixinConfigs': 'potatoptimize.mixins.json'
        ])
    }
}
