package dev.herbertofury.creeperella.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Vanilla ModelPart layers generated from the user-supplied OptiFine CEM models.
 * This removes any runtime OptiFine/EMF/ETF dependency while preserving the supplied geometry.
 * Generated by creeperella_work/generate_layers.py.
 */
public final class CreeperellaModelLayers {
    private CreeperellaModelLayers() {}

    public static LayerDefinition createFemaleLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_head2Cubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F))
                .texOffs(0, 16).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2 = vanilla_head.addOrReplaceChild("head2", custom_head2Cubes, PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_left_0Cubes = CubeListBuilder.create()
                .texOffs(0, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(16, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_hair_left_0 = custom_head2.addOrReplaceChild("hair_left", custom_head2_hair_left_0Cubes, PartPose.offsetAndRotation(4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_right_1Cubes = CubeListBuilder.create()
                .texOffs(96, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_hair_right_1 = custom_head2.addOrReplaceChild("hair_right", custom_head2_hair_right_1Cubes, PartPose.offsetAndRotation(-4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition custom_head2_left_eye_2 = custom_head2.addOrReplaceChild("left_eye", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, -4.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_eye_white_0Cubes = CubeListBuilder.create()
                .texOffs(26, 22).addBox(0.0F, -2.0F, -0.002F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_left_eye_2_l_eye_white_0 = custom_head2_left_eye_2.addOrReplaceChild("l_eye_white", custom_head2_left_eye_2_l_eye_white_0Cubes, PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_pupil_1Cubes = CubeListBuilder.create()
                .texOffs(27, 21).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_left_eye_2_l_pupil_1 = custom_head2_left_eye_2.addOrReplaceChild("l_pupil", custom_head2_left_eye_2_l_pupil_1Cubes, PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_eyebrow_2Cubes = CubeListBuilder.create()
                .texOffs(27, 20).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_left_eye_2_l_eyebrow_2 = custom_head2_left_eye_2.addOrReplaceChild("l_eyebrow", custom_head2_left_eye_2_l_eyebrow_2Cubes, PartPose.offsetAndRotation(1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition custom_head2_right_eye_3 = custom_head2.addOrReplaceChild("right_eye", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, -4.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_eye_white_0Cubes = CubeListBuilder.create()
                .texOffs(26, 22).addBox(-2.0F, -2.0F, -0.002F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_right_eye_3_r_eye_white_0 = custom_head2_right_eye_3.addOrReplaceChild("r_eye_white", custom_head2_right_eye_3_r_eye_white_0Cubes, PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_pupil_1Cubes = CubeListBuilder.create()
                .texOffs(27, 21).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_right_eye_3_r_pupil_1 = custom_head2_right_eye_3.addOrReplaceChild("r_pupil", custom_head2_right_eye_3_r_pupil_1Cubes, PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_eyebrow_2Cubes = CubeListBuilder.create()
                .texOffs(27, 20).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_right_eye_3_r_eyebrow_2 = custom_head2_right_eye_3.addOrReplaceChild("r_eyebrow", custom_head2_right_eye_3_r_eyebrow_2Cubes, PartPose.offsetAndRotation(-1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(32, 0).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(52, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(32, 12).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.25F))
                .texOffs(52, 8).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_breasts_0Cubes = CubeListBuilder.create()
                .texOffs(76, 0).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(76, 8).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body_breasts_0 = custom_body.addOrReplaceChild("breasts", custom_body_breasts_0Cubes, PartPose.offsetAndRotation(0.0F, -17.0F, -2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(16, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(32, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(48, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(64, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(80, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(96, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createBunnyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_head2Cubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F))
                .texOffs(0, 16).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2 = vanilla_head.addOrReplaceChild("head2", custom_head2Cubes, PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_left_0Cubes = CubeListBuilder.create()
                .texOffs(0, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(16, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_hair_left_0 = custom_head2.addOrReplaceChild("hair_left", custom_head2_hair_left_0Cubes, PartPose.offsetAndRotation(4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_right_1Cubes = CubeListBuilder.create()
                .texOffs(96, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_hair_right_1 = custom_head2.addOrReplaceChild("hair_right", custom_head2_hair_right_1Cubes, PartPose.offsetAndRotation(-4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition custom_head2_left_eye_2 = custom_head2.addOrReplaceChild("left_eye", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, -4.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_eye_white_0Cubes = CubeListBuilder.create()
                .texOffs(26, 22).addBox(0.0F, -2.0F, -0.002F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_left_eye_2_l_eye_white_0 = custom_head2_left_eye_2.addOrReplaceChild("l_eye_white", custom_head2_left_eye_2_l_eye_white_0Cubes, PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_pupil_1Cubes = CubeListBuilder.create()
                .texOffs(27, 21).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_left_eye_2_l_pupil_1 = custom_head2_left_eye_2.addOrReplaceChild("l_pupil", custom_head2_left_eye_2_l_pupil_1Cubes, PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_eyebrow_2Cubes = CubeListBuilder.create()
                .texOffs(27, 20).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_left_eye_2_l_eyebrow_2 = custom_head2_left_eye_2.addOrReplaceChild("l_eyebrow", custom_head2_left_eye_2_l_eyebrow_2Cubes, PartPose.offsetAndRotation(1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition custom_head2_right_eye_3 = custom_head2.addOrReplaceChild("right_eye", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, -4.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_eye_white_0Cubes = CubeListBuilder.create()
                .texOffs(26, 22).addBox(-2.0F, -2.0F, -0.002F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_right_eye_3_r_eye_white_0 = custom_head2_right_eye_3.addOrReplaceChild("r_eye_white", custom_head2_right_eye_3_r_eye_white_0Cubes, PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_pupil_1Cubes = CubeListBuilder.create()
                .texOffs(27, 21).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_right_eye_3_r_pupil_1 = custom_head2_right_eye_3.addOrReplaceChild("r_pupil", custom_head2_right_eye_3_r_pupil_1Cubes, PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_eyebrow_2Cubes = CubeListBuilder.create()
                .texOffs(27, 20).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_right_eye_3_r_eyebrow_2 = custom_head2_right_eye_3.addOrReplaceChild("r_eyebrow", custom_head2_right_eye_3_r_eyebrow_2Cubes, PartPose.offsetAndRotation(-1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_ear_4Cubes = CubeListBuilder.create()
                .texOffs(109, 31).addBox(-1.0F, -8.0F, 0.0F, 2.0F, 8.0F, 1.0F, new CubeDeformation(0.0F))
                .texOffs(109, 22).addBox(-1.0F, -8.0F, 0.0F, 2.0F, 8.0F, 1.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_left_ear_4 = custom_head2.addOrReplaceChild("left_ear", custom_head2_left_ear_4Cubes, PartPose.offsetAndRotation(2.0F, -7.0F, -1.0F, 0.0F, 0.0F, 0.174533F));
        CubeListBuilder custom_head2_right_ear_5Cubes = CubeListBuilder.create()
                .texOffs(101, 34).addBox(-1.0F, -5.0F, 0.0F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.0F))
                .texOffs(101, 28).addBox(-1.0F, -5.0F, 0.0F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_right_ear_5 = custom_head2.addOrReplaceChild("right_ear", custom_head2_right_ear_5Cubes, PartPose.offsetAndRotation(-2.0F, -7.0F, -1.0F, 0.0F, 0.0F, -0.174533F));
        CubeListBuilder custom_head2_right_ear_5_right_ear2_0Cubes = CubeListBuilder.create()
                .texOffs(117, 36).addBox(-1.0F, -3.0F, 0.0F, 2.0F, 3.0F, 1.0F, new CubeDeformation(0.0F))
                .texOffs(117, 32).addBox(-1.0F, -3.0F, 0.0F, 2.0F, 3.0F, 1.0F, new CubeDeformation(0.2505F));
        PartDefinition custom_head2_right_ear_5_right_ear2_0 = custom_head2_right_ear_5.addOrReplaceChild("right_ear2", custom_head2_right_ear_5_right_ear2_0Cubes, PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 1.570796F, 0.0F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(32, 0).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(52, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(32, 12).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.25F))
                .texOffs(52, 8).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_tail_0Cubes = CubeListBuilder.create()
                .texOffs(112, 0).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 8).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body_tail_0 = custom_body.addOrReplaceChild("tail", custom_body_tail_0Cubes, PartPose.offsetAndRotation(0.0F, -10.0F, 2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_body_breasts_1Cubes = CubeListBuilder.create()
                .texOffs(76, 0).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(76, 8).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body_breasts_1 = custom_body.addOrReplaceChild("breasts", custom_body_breasts_1Cubes, PartPose.offsetAndRotation(0.0F, -17.0F, -2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(16, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(32, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(48, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(64, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(80, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(96, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createBeeLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_head2Cubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F))
                .texOffs(0, 16).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2 = vanilla_head.addOrReplaceChild("head2", custom_head2Cubes, PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_left_0Cubes = CubeListBuilder.create()
                .texOffs(0, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(16, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_hair_left_0 = custom_head2.addOrReplaceChild("hair_left", custom_head2_hair_left_0Cubes, PartPose.offsetAndRotation(4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_right_1Cubes = CubeListBuilder.create()
                .texOffs(96, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_head2_hair_right_1 = custom_head2.addOrReplaceChild("hair_right", custom_head2_hair_right_1Cubes, PartPose.offsetAndRotation(-4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition custom_head2_left_eye_2 = custom_head2.addOrReplaceChild("left_eye", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, -4.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_eye_white_0Cubes = CubeListBuilder.create()
                .texOffs(26, 22).addBox(0.0F, -2.0F, -0.002F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_left_eye_2_l_eye_white_0 = custom_head2_left_eye_2.addOrReplaceChild("l_eye_white", custom_head2_left_eye_2_l_eye_white_0Cubes, PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_pupil_1Cubes = CubeListBuilder.create()
                .texOffs(27, 21).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_left_eye_2_l_pupil_1 = custom_head2_left_eye_2.addOrReplaceChild("l_pupil", custom_head2_left_eye_2_l_pupil_1Cubes, PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_eye_2_l_eyebrow_2Cubes = CubeListBuilder.create()
                .texOffs(27, 20).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_left_eye_2_l_eyebrow_2 = custom_head2_left_eye_2.addOrReplaceChild("l_eyebrow", custom_head2_left_eye_2_l_eyebrow_2Cubes, PartPose.offsetAndRotation(1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition custom_head2_right_eye_3 = custom_head2.addOrReplaceChild("right_eye", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, -4.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_eye_white_0Cubes = CubeListBuilder.create()
                .texOffs(26, 22).addBox(-2.0F, -2.0F, -0.002F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_right_eye_3_r_eye_white_0 = custom_head2_right_eye_3.addOrReplaceChild("r_eye_white", custom_head2_right_eye_3_r_eye_white_0Cubes, PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_pupil_1Cubes = CubeListBuilder.create()
                .texOffs(27, 21).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_right_eye_3_r_pupil_1 = custom_head2_right_eye_3.addOrReplaceChild("r_pupil", custom_head2_right_eye_3_r_pupil_1Cubes, PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_eye_3_r_eyebrow_2Cubes = CubeListBuilder.create()
                .texOffs(27, 20).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.005F));
        PartDefinition custom_head2_right_eye_3_r_eyebrow_2 = custom_head2_right_eye_3.addOrReplaceChild("r_eyebrow", custom_head2_right_eye_3_r_eyebrow_2Cubes, PartPose.offsetAndRotation(-1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_ear_4Cubes = CubeListBuilder.create()
                .texOffs(102, 2).addBox(0.0F, -2.0F, -3.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_left_ear_4 = custom_head2.addOrReplaceChild("left_ear", custom_head2_left_ear_4Cubes, PartPose.offsetAndRotation(2.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_ear_5Cubes = CubeListBuilder.create()
                .texOffs(102, 4).addBox(0.0F, -2.0F, -3.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head2_right_ear_5 = custom_head2.addOrReplaceChild("right_ear", custom_head2_right_ear_5Cubes, PartPose.offsetAndRotation(-2.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(32, 0).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(52, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(32, 12).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.25F))
                .texOffs(52, 8).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_tail_0Cubes = CubeListBuilder.create()
                .texOffs(110, 0).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 5.0F, new CubeDeformation(0.0F))
                .texOffs(121, 3).addBox(-0.5F, 0.0F, 5.0F, 1.0F, 0.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(111, 2).addBox(0.0F, -0.5F, 5.0F, 0.0F, 1.0F, 2.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_tail_0 = custom_body.addOrReplaceChild("tail", custom_body_tail_0Cubes, PartPose.offsetAndRotation(0.0F, -10.0F, 2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_body_breasts_1Cubes = CubeListBuilder.create()
                .texOffs(76, 0).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(76, 8).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_body_breasts_1 = custom_body.addOrReplaceChild("breasts", custom_body_breasts_1Cubes, PartPose.offsetAndRotation(0.0F, -17.0F, -2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_body_left_wings_2Cubes = CubeListBuilder.create()
                .texOffs(113, 9).addBox(0.0F, 0.0F, 0.0F, 6.0F, 6.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_left_wings_2 = custom_body.addOrReplaceChild("left_wings", custom_body_left_wings_2Cubes, PartPose.offsetAndRotation(0.0F, -19.0F, 2.0F, 0.392699F, -0.392699F, -0.392699F));
        CubeListBuilder custom_body_right_wings_3Cubes = CubeListBuilder.create()
                .texOffs(113, 15).addBox(-6.0F, 0.0F, 0.0F, 6.0F, 6.0F, 0.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_right_wings_3 = custom_body.addOrReplaceChild("right_wings", custom_body_right_wings_3Cubes, PartPose.offsetAndRotation(0.0F, -19.0F, 2.0F, 0.392699F, 0.392699F, 0.392699F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(16, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(32, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(48, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(64, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(80, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(96, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(112, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.25F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createFemaleChargeLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_head2Cubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2 = vanilla_head.addOrReplaceChild("head2", custom_head2Cubes, PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_left_0Cubes = CubeListBuilder.create()
                .texOffs(0, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_hair_left_0 = custom_head2.addOrReplaceChild("hair_left", custom_head2_hair_left_0Cubes, PartPose.offsetAndRotation(4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_right_1Cubes = CubeListBuilder.create()
                .texOffs(96, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_hair_right_1 = custom_head2.addOrReplaceChild("hair_right", custom_head2_hair_right_1Cubes, PartPose.offsetAndRotation(-4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(32, 0).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.5F))
                .texOffs(52, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.501F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_breasts_0Cubes = CubeListBuilder.create()
                .texOffs(76, 0).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_breasts_0 = custom_body.addOrReplaceChild("breasts", custom_body_breasts_0Cubes, PartPose.offsetAndRotation(0.0F, -17.0F, -2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(32, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(64, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(96, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createBunnyChargeLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_head2Cubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2 = vanilla_head.addOrReplaceChild("head2", custom_head2Cubes, PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_left_0Cubes = CubeListBuilder.create()
                .texOffs(0, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_hair_left_0 = custom_head2.addOrReplaceChild("hair_left", custom_head2_hair_left_0Cubes, PartPose.offsetAndRotation(4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_right_1Cubes = CubeListBuilder.create()
                .texOffs(96, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_hair_right_1 = custom_head2.addOrReplaceChild("hair_right", custom_head2_hair_right_1Cubes, PartPose.offsetAndRotation(-4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_ear_2Cubes = CubeListBuilder.create()
                .texOffs(109, 31).addBox(-1.0F, -8.0F, 0.0F, 2.0F, 8.0F, 1.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_left_ear_2 = custom_head2.addOrReplaceChild("left_ear", custom_head2_left_ear_2Cubes, PartPose.offsetAndRotation(2.0F, -7.0F, -1.0F, 0.0F, 0.0F, 0.174533F));
        CubeListBuilder custom_head2_right_ear_3Cubes = CubeListBuilder.create()
                .texOffs(101, 34).addBox(-1.0F, -5.0F, 0.0F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_right_ear_3 = custom_head2.addOrReplaceChild("right_ear", custom_head2_right_ear_3Cubes, PartPose.offsetAndRotation(-2.0F, -7.0F, -1.0F, 0.0F, 0.0F, -0.174533F));
        CubeListBuilder custom_head2_right_ear_3_right_ear2_0Cubes = CubeListBuilder.create()
                .texOffs(117, 36).addBox(-1.0F, -3.0F, 0.0F, 2.0F, 3.0F, 1.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_right_ear_3_right_ear2_0 = custom_head2_right_ear_3.addOrReplaceChild("right_ear2", custom_head2_right_ear_3_right_ear2_0Cubes, PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 1.570796F, 0.0F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(32, 0).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.5F))
                .texOffs(52, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.501F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_tail_0Cubes = CubeListBuilder.create()
                .texOffs(112, 0).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_tail_0 = custom_body.addOrReplaceChild("tail", custom_body_tail_0Cubes, PartPose.offsetAndRotation(0.0F, -10.0F, 2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_body_breasts_1Cubes = CubeListBuilder.create()
                .texOffs(76, 0).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_breasts_1 = custom_body.addOrReplaceChild("breasts", custom_body_breasts_1Cubes, PartPose.offsetAndRotation(0.0F, -17.0F, -2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(32, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(64, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(96, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createBeeChargeLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_head2Cubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2 = vanilla_head.addOrReplaceChild("head2", custom_head2Cubes, PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_left_0Cubes = CubeListBuilder.create()
                .texOffs(0, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_hair_left_0 = custom_head2.addOrReplaceChild("hair_left", custom_head2_hair_left_0Cubes, PartPose.offsetAndRotation(4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_hair_right_1Cubes = CubeListBuilder.create()
                .texOffs(96, 40).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_hair_right_1 = custom_head2.addOrReplaceChild("hair_right", custom_head2_hair_right_1Cubes, PartPose.offsetAndRotation(-4.0F, -6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_left_ear_2Cubes = CubeListBuilder.create()
                .texOffs(102, 2).addBox(0.0F, -2.0F, -3.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_left_ear_2 = custom_head2.addOrReplaceChild("left_ear", custom_head2_left_ear_2Cubes, PartPose.offsetAndRotation(2.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head2_right_ear_3Cubes = CubeListBuilder.create()
                .texOffs(102, 4).addBox(0.0F, -2.0F, -3.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head2_right_ear_3 = custom_head2.addOrReplaceChild("right_ear", custom_head2_right_ear_3Cubes, PartPose.offsetAndRotation(-2.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(32, 0).addBox(-3.0F, -20.0F, -2.0F, 6.0F, 8.0F, 4.0F, new CubeDeformation(0.5F))
                .texOffs(52, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.501F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_tail_0Cubes = CubeListBuilder.create()
                .texOffs(110, 0).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 5.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_tail_0 = custom_body.addOrReplaceChild("tail", custom_body_tail_0Cubes, PartPose.offsetAndRotation(0.0F, -10.0F, 2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_body_breasts_1Cubes = CubeListBuilder.create()
                .texOffs(76, 0).addBox(-4.0F, -2.0F, -2.0F, 8.0F, 4.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_breasts_1 = custom_body.addOrReplaceChild("breasts", custom_body_breasts_1Cubes, PartPose.offsetAndRotation(0.0F, -17.0F, -2.0F, 0.392699F, 0.0F, 0.0F));
        CubeListBuilder custom_body_left_wings_2Cubes = CubeListBuilder.create()
                .texOffs(113, 18).addBox(0.0F, 0.0F, 0.0F, 6.0F, 6.0F, 0.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_left_wings_2 = custom_body.addOrReplaceChild("left_wings", custom_body_left_wings_2Cubes, PartPose.offsetAndRotation(0.0F, -19.0F, 2.0F, 0.392699F, -0.392699F, -0.392699F));
        CubeListBuilder custom_body_right_wings_3Cubes = CubeListBuilder.create()
                .texOffs(113, 24).addBox(-6.0F, 0.0F, 0.0F, 6.0F, 6.0F, 0.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_right_wings_3 = custom_body.addOrReplaceChild("right_wings", custom_body_right_wings_3Cubes, PartPose.offsetAndRotation(0.0F, -19.0F, 2.0F, 0.392699F, 0.392699F, 0.392699F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 52).addBox(-4.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(32, 52).addBox(0.0F, -8.0F, 2.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(64, 52).addBox(-4.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(96, 52).addBox(0.0F, -8.0F, -6.0F, 4.0F, 8.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createCherryLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_headCubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -26.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head = vanilla_head.addOrReplaceChild("head", custom_headCubes, PartPose.offsetAndRotation(0.0F, 18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head_bone8_0Cubes = CubeListBuilder.create()
                .texOffs(11, 0).addBox(8.0F, -2.0F, 2.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(15, 16).addBox(1.0F, -10.0F, 1.0F, 5.0F, 5.0F, 5.0F, new CubeDeformation(0.0F))
                .texOffs(9, -1).addBox(6.0F, -4.0F, 3.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F))
                .texOffs(9, -1).addBox(6.0F, -1.0F, -1.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F))
                .texOffs(8, 0).addBox(4.0F, -7.0F, 4.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_head_bone8_0 = custom_head.addOrReplaceChild("bone8", custom_head_bone8_0Cubes, PartPose.offsetAndRotation(0.0F, -18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head_bone_1Cubes = CubeListBuilder.create()
                .texOffs(16, 4).addBox(10.0F, -8.0F, 0.0F, 0.01F, 9.0F, 9.0F, new CubeDeformation(0.0F)) /* per-face CEM UV approximated at face origin */;
        PartDefinition custom_head_bone_1 = custom_head.addOrReplaceChild("bone", custom_head_bone_1Cubes, PartPose.offsetAndRotation(-13.0F, -21.0F, 1.0F, 0.0F, 0.872665F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(16, 16).addBox(-4.0F, -18.0F, -2.0F, 8.0F, 12.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_bone2_0Cubes = CubeListBuilder.create()
                .texOffs(32, 13).addBox(-1.0F, -1.0F, -6.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_bone2_0 = custom_body.addOrReplaceChild("bone2", custom_body_bone2_0Cubes, PartPose.offsetAndRotation(3.0F, -17.0F, 0.0F, 0.493929F, -0.4703F, -0.239323F));
        CubeListBuilder custom_body_bone7_1Cubes = CubeListBuilder.create()
                .texOffs(24, 20).addBox(-1.0F, -1.0F, -6.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_bone7_1 = custom_body.addOrReplaceChild("bone7", custom_body_bone7_1Cubes, PartPose.offsetAndRotation(1.0F, -18.0F, -2.0F, 0.523599F, 0.0F, 0.0F));
        CubeListBuilder custom_body_bone3_2Cubes = CubeListBuilder.create()
                .texOffs(14, 8).addBox(-3.0F, 0.0F, -5.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_bone3_2 = custom_body.addOrReplaceChild("bone3", custom_body_bone3_2Cubes, PartPose.offsetAndRotation(0.0F, -13.0F, -2.0F, 0.0F, 0.654498F, 0.0F));
        CubeListBuilder custom_body_bone5_3Cubes = CubeListBuilder.create()
                .texOffs(20, 16).addBox(-2.0F, -2.5F, -2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_bone5_3 = custom_body.addOrReplaceChild("bone5", custom_body_bone5_3Cubes, PartPose.offsetAndRotation(2.0F, -15.84267F, -1.34219F, -0.958139F, -0.071455F, -0.050139F));
        CubeListBuilder custom_body_bone6_4Cubes = CubeListBuilder.create()
                .texOffs(24, 16).addBox(-2.0F, -2.5F, -2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_body_bone6_4 = custom_body.addOrReplaceChild("bone6", custom_body_bone6_4Cubes, PartPose.offsetAndRotation(-2.0F, -15.84267F, -1.34219F, -0.958139F, 0.071455F, 0.050139F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(-4.0F, -6.0F, 2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(0.0F, -6.0F, 2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(-4.0F, -6.0F, -6.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(0.0F, -6.0F, -6.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.0F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    public static LayerDefinition createCherryChargeLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition vanilla_head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 6.0F, 0.0F));
        PartDefinition vanilla_right_hind_leg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_left_hind_leg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, 4.0F));
        PartDefinition vanilla_right_front_leg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.0F, -4.0F));
        PartDefinition vanilla_left_front_leg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create(), PartPose.offset(2.0F, 18.0F, -4.0F));

        CubeListBuilder custom_headCubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4.0F, -26.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head = vanilla_head.addOrReplaceChild("head", custom_headCubes, PartPose.offsetAndRotation(0.0F, 18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head_bone8_0Cubes = CubeListBuilder.create()
                .texOffs(11, 0).addBox(8.0F, -2.0F, 2.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.5F))
                .texOffs(15, 16).addBox(1.0F, -10.0F, 1.0F, 5.0F, 5.0F, 5.0F, new CubeDeformation(0.5F))
                .texOffs(9, -1).addBox(6.0F, -4.0F, 3.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.5F))
                .texOffs(9, -1).addBox(6.0F, -1.0F, -1.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.5F))
                .texOffs(8, 0).addBox(4.0F, -7.0F, 4.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_head_bone8_0 = custom_head.addOrReplaceChild("bone8", custom_head_bone8_0Cubes, PartPose.offsetAndRotation(0.0F, -18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_head_bone_1Cubes = CubeListBuilder.create()
                .texOffs(16, 4).addBox(10.0F, -8.0F, 0.0F, 0.01F, 9.0F, 9.0F, new CubeDeformation(0.5F)) /* per-face CEM UV approximated at face origin */;
        PartDefinition custom_head_bone_1 = custom_head.addOrReplaceChild("bone", custom_head_bone_1Cubes, PartPose.offsetAndRotation(-13.0F, -21.0F, 1.0F, 0.0F, 0.872665F, 0.0F));
        CubeListBuilder custom_bodyCubes = CubeListBuilder.create()
                .texOffs(16, 16).addBox(-4.0F, -18.0F, -2.0F, 8.0F, 12.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body = vanilla_body.addOrReplaceChild("body", custom_bodyCubes, PartPose.offsetAndRotation(0.0F, 18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_body_bone2_0Cubes = CubeListBuilder.create()
                .texOffs(32, 13).addBox(-1.0F, -1.0F, -6.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_bone2_0 = custom_body.addOrReplaceChild("bone2", custom_body_bone2_0Cubes, PartPose.offsetAndRotation(3.0F, -17.0F, 0.0F, 0.493929F, -0.4703F, -0.239323F));
        CubeListBuilder custom_body_bone7_1Cubes = CubeListBuilder.create()
                .texOffs(24, 20).addBox(-1.0F, -1.0F, -6.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_bone7_1 = custom_body.addOrReplaceChild("bone7", custom_body_bone7_1Cubes, PartPose.offsetAndRotation(1.0F, -18.0F, -2.0F, 0.523599F, 0.0F, 0.0F));
        CubeListBuilder custom_body_bone3_2Cubes = CubeListBuilder.create()
                .texOffs(14, 8).addBox(-3.0F, 0.0F, -5.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_bone3_2 = custom_body.addOrReplaceChild("bone3", custom_body_bone3_2Cubes, PartPose.offsetAndRotation(0.0F, -13.0F, -2.0F, 0.0F, 0.654498F, 0.0F));
        CubeListBuilder custom_body_bone5_3Cubes = CubeListBuilder.create()
                .texOffs(20, 16).addBox(-2.0F, -2.5F, -2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_bone5_3 = custom_body.addOrReplaceChild("bone5", custom_body_bone5_3Cubes, PartPose.offsetAndRotation(2.0F, -15.84267F, -1.34219F, -0.958139F, -0.071455F, -0.050139F));
        CubeListBuilder custom_body_bone6_4Cubes = CubeListBuilder.create()
                .texOffs(24, 16).addBox(-2.0F, -2.5F, -2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_body_bone6_4 = custom_body.addOrReplaceChild("bone6", custom_body_bone6_4Cubes, PartPose.offsetAndRotation(-2.0F, -15.84267F, -1.34219F, -0.958139F, 0.071455F, 0.050139F));
        CubeListBuilder custom_leg1Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(-4.0F, -6.0F, 2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg1 = vanilla_right_hind_leg.addOrReplaceChild("leg1", custom_leg1Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg2Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(0.0F, -6.0F, 2.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg2 = vanilla_left_hind_leg.addOrReplaceChild("leg2", custom_leg2Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg3Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(-4.0F, -6.0F, -6.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg3 = vanilla_right_front_leg.addOrReplaceChild("leg3", custom_leg3Cubes, PartPose.offsetAndRotation(2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        CubeListBuilder custom_leg4Cubes = CubeListBuilder.create()
                .texOffs(0, 16).addBox(0.0F, -6.0F, -6.0F, 4.0F, 6.0F, 4.0F, new CubeDeformation(0.5F));
        PartDefinition custom_leg4 = vanilla_left_front_leg.addOrReplaceChild("leg4", custom_leg4Cubes, PartPose.offsetAndRotation(-2.0F, 6.0F, 4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
